# Auto-generated by 1_prepare.ps1 (v3) -- do not edit manually
# Refs:
#   PyTorch Windows FAQ : https://docs.pytorch.org/docs/2.11/notes/windows.html
#   TorchAudio Windows  : https://docs.pytorch.org/audio/2.8/build.windows.html
# CUDA version : 12.9
# cuDNN version: 9.21.1
# Generated   : 2026-05-01 09:23

# --- MSVC: vcvarsall.bat path (used by 2_build.ps1 to activate full MSVC env) ---
# Per official docs: use vcvarsall.bat x64 to enable the MSVC x64 toolset
$script:VcvarsPath               = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvarsall.bat"
$script:ChosenClExe              = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe"

# --- cuDNN ---
$env:CUDNN_ROOT                  = "C:\\Program Files\\NVIDIA\\CUDNN\\v9.21"
$env:CUDNN_ROOT_DIR              = "C:\\Program Files\\NVIDIA\\CUDNN\\v9.21"
$env:CUDNN_INCLUDE_PATH          = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\include"
$env:CUDNN_LIBRARY_PATH          = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\lib\\x64"
$env:CUDNN_LIBRARY               = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\lib\\x64\\cudnn.lib"

# --- CUDA ---
$env:CUDA_HOME                   = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9"
$env:CUDA_PATH                   = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9"
$env:TORCH_CUDA_ARCH_LIST        = "6.0;12.0"

# --- MSVC host compiler ---
$env:CUDAHOSTCXX                 = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe"
$env:CXX                         = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe"
$env:CC                          = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe"
$env:CMAKE_CUDA_HOST_COMPILER    = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe"

# --- CMAKE_GENERATOR: Ninja required per Windows FAQ ---
# "Visual Studio doesn't support parallel custom task currently"
$env:CMAKE_GENERATOR             = "Ninja"

# --- MKL paths (Windows FAQ: CMAKE_INCLUDE_PATH + LIB must be set) ---
$env:CMAKE_INCLUDE_PATH          = ""
$env:LIB                         = ";$env:LIB"

# --- MAGMA (optional GPU linear algebra -- Windows FAQ) ---
$env:MAGMA_HOME                  = ""

# --- CMAKE_PREFIX_PATH: cuDNN + conda + CUDA ---
$env:CMAKE_PREFIX_PATH           = "C:\\Program Files\\NVIDIA\\CUDNN\\v9.21;C:\\ProgramData\\miniconda3\\envs\\Lib\\site-packages;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9"

# --- PATH: rebuilt at load time from live session PATH ---
$_cleanPath = $env:PATH -replace ('(?i)' + [regex]::Escape("C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA") + '\\v[^;]+;'), ''
$env:PATH = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\libnvvp;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.9\\bin;C:\\ProgramData\\miniconda3\\envs\Scripts;C:\\ProgramData\\miniconda3\\envs\Library\bin;$_cleanPath"

# --- Build feature flags ---
$env:USE_CUDA                    = "1"
$env:USE_CUDNN                   = "1"
$env:USE_FLASH_ATTENTION         = "1"
$env:USE_MKLDNN                  = "1"
$env:USE_DISTRIBUTED             = "1"
$env:USE_GLOO                    = "1"
$env:USE_NUMPY                   = "1"
$env:USE_KINETO                  = "1"
$env:USE_TEST                    = "0"

# --- Parallelism ---
$env:CMAKE_BUILD_PARALLEL_LEVEL  = "18"
$env:MAX_JOBS                    = "8"

# --- NVCC flags ---
# --diag-suppress=20092 : clusterlaunchcontrol.h ASM constraint error on sm_60
$env:NVCC_APPEND_FLAGS           = "--diag-suppress=20092"
$env:REL_WITH_DEB_INFO           = "0"

# --- MSVC ICE workaround (/Od on release build for sdp.cpp) ---
$env:EXTRA_CAFFE2_CMAKE_FLAGS    = "-DCMAKE_CXX_FLAGS_RELEASE=/Od"

# --- Shared with other scripts ---
$script:CondaPython              = "C:\\ProgramData\\miniconda3\\envs\\pytorch-build\\python.exe"
$script:PyTorchDir               = "D:\\Workplace\\PyTorch-build\\pytorch"
$script:CondaEnv                 = "pytorch-build"
$script:CondaPrefix              = "C:\\ProgramData\\miniconda3\\envs"
